#!/usr/bin/env bash
# graph.sh — Thanos context-graph adapter. Build a structural import/reference map of the repo
# so REALITY can be richer and cheaper than dumping raw files. Language-agnostic, best-effort.
#   --detect                 0 ready · non-zero blocked (+ hint on stderr)
#   [out-prefix]             writes <prefix>.json + <prefix>.md (default .thanos/proof/context-graph)
set -euo pipefail
_err(){ echo "graph: $*" >&2; }
_info(){ echo "graph: $*" >&2; }

detect() {
  if ! command -v python3 &>/dev/null; then
    _err "python3 not found (needed to build the graph). Install Python 3."
    return 1
  fi
  _info "ready — python3 $(python3 --version 2>&1 | awk '{print $2}')$(command -v git &>/dev/null && echo ' + git' || echo '')"
  return 0
}

main() {
  local first="${1:-}"
  [[ "$first" == "--detect" ]] && { detect; exit $?; }
  if ! detect >/dev/null 2>&1; then detect || true; _err "blocked"; exit 1; fi

  local prefix="${1:-.thanos/proof/context-graph}"
  mkdir -p "$(dirname "$prefix")"

  # File list: prefer git (respects .gitignore), else find.
  local listing
  if command -v git &>/dev/null && git rev-parse --is-inside-work-tree &>/dev/null; then
    listing=$(git ls-files)
  else
    listing=$(find . -type f -not -path './.git/*' -not -path './node_modules/*' -not -path './.thanos/*')
  fi

  _info "building context graph → ${prefix}.json + ${prefix}.md"
  # NOTE: pass the listing via a temp file (argv), NOT stdin — the <<PYEOF heredoc
  # already claims python's stdin, so a piped listing would be silently ignored.
  local tmplist; tmplist=$(mktemp)
  trap 'rm -f "$tmplist"' EXIT   # clean up even if the python pass fails under set -e
  printf '%s\n' "$listing" > "$tmplist"
  python3 - "$prefix" "$tmplist" <<'PYEOF'
import sys, re, json, os
from collections import defaultdict, Counter

prefix = sys.argv[1]
with open(sys.argv[2], 'r', encoding='utf-8', errors='ignore') as lf:
    files = [l.strip() for l in lf if l.strip()]

SRC_EXT = {'.js','.jsx','.ts','.tsx','.mjs','.cjs','.py','.go','.rs','.rb','.java',
           '.c','.h','.cpp','.hpp','.php','.swift','.kt','.sh','.vue','.svelte'}
SKIP_DIR = ('node_modules/', '.git/', '.thanos/', 'dist/', 'build/', '.next/')

patterns = [
    re.compile(r'''import\s+.*?from\s+['"]([^'"]+)['"]'''),       # JS/TS import x from 'y'
    re.compile(r'''require\(\s*['"]([^'"]+)['"]\s*\)'''),         # CommonJS require('y')
    re.compile(r'''^\s*from\s+([\w\.]+)\s+import''', re.M),       # Python from x import
    re.compile(r'''^\s*import\s+([\w\.]+)''', re.M),              # Python/Go/Java import x
    re.compile(r'''#include\s+["<]([^">]+)[">]'''),              # C/C++ include
    re.compile(r'''^\s*use\s+([\w:]+)''', re.M),                 # Rust use
]

edges = {}
ref_counter = Counter()
clusters = defaultdict(int)
considered = 0

for f in files:
    if any(s in f for s in SKIP_DIR): continue
    _, ext = os.path.splitext(f)
    if ext.lower() not in SRC_EXT: continue
    try:
        with open(f, 'r', encoding='utf-8', errors='ignore') as fh:
            text = fh.read(200000)
    except Exception:
        continue
    considered += 1
    clusters[os.path.dirname(f) or '.'] += 1
    refs = set()
    for pat in patterns:
        for m in pat.findall(text):
            refs.add(m)
    edges[f] = sorted(refs)
    for r in refs:
        ref_counter[r] += 1

# Hubs = most-referenced modules (the things to touch carefully)
hubs = ref_counter.most_common(15)

graph = {
    "files_total": len(files),
    "source_files": considered,
    "nodes": len(edges),
    "clusters": dict(sorted(clusters.items(), key=lambda kv: -kv[1])),
    "hubs": [{"module": m, "referenced_by": c} for m, c in hubs],
    "edges": edges,
}
with open(prefix + ".json", "w") as out:
    json.dump(graph, out, indent=2)

with open(prefix + ".md", "w") as out:
    out.write("# 🕸️ Context Graph\n\n")
    out.write(f"- Files in tree: **{len(files)}**\n- Source files analyzed: **{considered}**\n")
    out.write(f"- Graph nodes (files with refs): **{len(edges)}**\n\n")
    out.write("## Clusters (by source file count)\n\n")
    for d, n in list(sorted(clusters.items(), key=lambda kv: -kv[1]))[:20]:
        out.write(f"- `{d}` — {n}\n")
    out.write("\n## Hubs (most-referenced modules — touch carefully)\n\n")
    for m, c in hubs:
        out.write(f"- `{m}` ← referenced by {c}\n")
    out.write("\n_Generated by Thanos graph.sh — feed the summary into REALITY; read full files only for nodes the goal touches._\n")

print(f"graph: ok — {considered} source files, {len(edges)} nodes", file=sys.stderr)
PYEOF
  rm -f "$tmplist"

  [[ -s "${prefix}.json" && -s "${prefix}.md" ]] || { _err "graph not produced"; exit 1; }
  echo "${prefix}.json"
}
main "$@"
